### ISSUE TITLE
Improve/Add projects page

### ISSUE THREAD

**Issue by pranavk** [glugnith/glug.nith.ac.in#18]
We had a proejcts page intially on glug.nith.ac.in. This was a wonderful thing that newcomers can have a look at and look at the source code. But we removed this page because that page was not managed properly.

I am thinking of creating a Projects page again on the site with following specification ---
The project page should have a project leader link that would mention the name of the project leader with some description about the project and and "How to contribute" link containing a begineer guide to contribute to this project.

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
