### ISSUE TITLE
Indent whole source code/ Code Scrubbing

### ISSUE THREAD

**Issue by pranavk** [glugnith/glug.nith.ac.in#20]
It would be better if we indent the whole source code of the website, it would help new contributors to quickly dive in.

Moreover, we need to scrub the code(remove stupid comments, add new comments at appropriate places etc. )

**Comment by divyanshu013** [comment]
This should be an easy task if anyone is interested :wink:

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
