### ISSUE TITLE
need a page to request for email alias

### ISSUE THREAD

**Issue by pranavk** [glugnith/glug.nith.ac.in#23]
I have set up the mail server on the server again but this time emails won't be stored on the server but rather would just be forwarded to the email address that the member provide.

Lets create a form which asks for following information.

Name 
Roll no.
Branch
Email address to forward to
Requested email alias
Why you want an alias ? (Requester will have to answer this and convince that he should be granted an email alias)

**Comment by rohanjaswal2507** [comment]
http://glug.nith.ac.in/alias_request.php
