### ISSUE TITLE
A page containing useful links for beginners to start learning about some technology

### ISSUE THREAD

**Issue by divyanshu013** [glugnith/glug.nith.ac.in#32]
The open-source world is quite vast and it's quite difficult for a newcomer to start with. This page should contain useful links that people might find useful (videos or websites) in order to get started.
This should be designed in a way such that one doesn't get overwhelmed with the information. This should be an easy task if anyone is interested; perhaps GLUG(ers) can work on this in a team.

**Comment by Rishabh04-02** [comment]
Sir can you give some example, that what type of links we need to put to that page.
can we include sites like https://www.hackster.io/ and what about learning sites like https://edx.org

**Comment by divyanshu013** [comment]
This could be written simply in markdown to allow ease of access when changing things or it can be made a separate webpage. It can be displayed in an interactive manner eg. using flowcharts or some other apt design.

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
