### ISSUE TITLE
Revamping the website

### ISSUE THREAD

**Issue by divyanshu013** [glugnith/glug.nith.ac.in#33]
The website doesn't looks good in smaller screens (mobile devices). We should try to fix this. I think the best way would be to use a responsive layout using bootstrap. There are lots of free templates available (which may be tweaked) or we can work one of our own out. This task would take quite some time and effort but it would be quite fun :wink: 
Please note that the design of the website should reflect the spirit of FOSS.

**Comment by gdad-s-river** [comment]
Whenever this Task gets started, I would like to be a part of it.

**Comment by Rishabh04-02** [comment]
Does this means that we need a new layout for glug website which will be compatible and reflect the spirit of foss.

**Comment by divyanshu013** [comment]
Yes @Rishabh04-02 pretty much. Let's start by deciding on a UI mockup to cover all the aspects. @sagarkarira what would you recommend to use for this project?

**Comment by gdad-s-river** [comment]
@divyanshu013 @sagarkarira , creating a style guides (fonts, colors, custom components), wireframes (a basic structure of the whole site in terms of where a header, an article, text, images, footer, article, other sections are) and a visual design (complete mockup design on photoshop in color), should, I guess be the first professional step in revamping the site.

**Comment by lokeshh** [comment]
@gdad-s-river, @Rishabh04-02 I had a chat with @sagarkarira and we building the new website using [Lektor](www.getlektor.org). I've created a separate repo for this at https://github.com/lokeshh/upgrade_glugnith. Let's do it.

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
