### ISSUE TITLE
Dynamic members page on the site

### ISSUE THREAD

**Issue by Rishabh04-02** [glugnith/glug.nith.ac.in#41]
members page is at http://glug.nith.ac.in/members
and this page is vary basic so it should be dynamic.

**Comment by divyanshu013** [comment]
Actually, we don't need a members specific page. It's done just to allow them to get started to contributing code and seeing it live on the web. If we create such a page, it might get flooded with members pages. @sagarkarira what do you say?

**Comment by Rishabh04-02** [comment]
Thanks, got it.

**Comment by sagarkarira** [comment]
Yeah we need a new page for the members which should look good.

**Comment by Rishabh04-02** [comment]
The page which is at - http://glug.nith.ac.in/members/
is not in this repository. Do we need to create a new page now?

**Comment by divyanshu013** [comment]
A simple single page design should be enough I think. Check this out:

![screenshot from 2016-02-15 17-20-45](https://cloud.githubusercontent.com/assets/6682655/13047921/6dea8202-d408-11e5-83d8-2d12e0d113b0.png)

http://blackrockdigital.github.io/startbootstrap-agency/

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
