### ISSUE TITLE
Don't see the glug logo when running repository locally

### ISSUE THREAD

**Issue by lokeshh** [glugnith/glug.nith.ac.in#45]
When running the website locally I do not get the Glug logo. Instead I just see the text "Glug logo"

![screenshot](http://i65.tinypic.com/a9l6hl.png)

Any idea what's wrong?

**Comment by divyanshu013** [comment]
The logo's src="images/background". The background directory isn't included in the repository that's why it shows nothing. You can fix it by creating this directory in your local and copying the logo. What you should do is to include the new logo in the repo which will also fix #19
