### ISSUE TITLE
Updating readme to be more specific about getting started

### ISSUE THREAD

**Issue by kumarmj** [glugnith/glug.nith.ac.in#50]
To be truthful **How do I get started** do not contain any command about how to clone, run project and push changes

**Cloning Project**
`$ git clone https://github.com/glugnith/glug.nith.ac.in.git`

**Running project on linux using lamp**
`$ <editor> /etc/apache2/sites-enabled/000-default`

change **document root** to project directory
or 
copy project source code in `/var/www`

**Push Changes**
`$ git push origin master`

feel free to add your views

**Comment by divyanshu013** [comment]
Updated repo at https://github.com/Nithmr/glugWebsite
